version: '2'
services:
  helloZk:
    container_name: helloZk
    image: zookeeper:3.4.11
    ports:
      - 2181:2181
    labels:
      - project.source=public-image
      - project.owner=struy

  helloService:
    container_name: helloService
    image: docker.dapeng.example/hello-service:1.0-SNAPSHOT
    volumes:
      - "/data/logs/dapeng/hello-service:/dapeng-container/logs"
    environment:
      - soa_monitor_enable=false
      - soa_transactional_enable=false
      - soa_core_pool_size=100
      - LANG=zh_CN.UTF-8
      - TZ=CST-8
      - soa_container_port=${hello_service_port}
      - soa_container_ip=${hello_service_ip}
      - soa_zookeeper_host=${soa_zookeeper_host}
    ports:
      - "${hello_service_port}:${hello_service_port}"
    labels:
      - project.source=https://github.com/dapeng-soa/dapeng-hello.git
      - project.depends=helloZk
      - project.owner=struy