version: '2'
services:
  helloZk:
    container_name: helloZk
    image: zookeeper:3.4.11
    ports:
      - 2181:2181
    labels:
      - project.source=public-image
      - project.owner=struy

  helloService:
    container_name: helloService
    image: docker.dapeng.example/hello-service:1.0-SNAPSHOT
    volumes:
      - "/Users/ever/dev/data/logs/dapeng/hello-service:/dapeng-container/logs"
    environment:
      - soa_monitor_enable=false
      - soa_transactional_enable=false
      - soa_core_pool_size=100
      - LANG=zh_CN.UTF-8
      - TZ=CST-8
      - soa_container_port=9696
      - host_ip=192.168.0.104
      - soa_zookeeper_host=192.168.0.104:2181
    ports:
      - "9696:9696"
    labels:
      - project.source=https://github.com/dapeng-soa/dapeng-hello.git
      - project.depends=helloZk
      - project.owner=struy

  mysql:
    container_name: mysql
    image: mariadb:10.2.13
    restart: on-failure:3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=CST-8
      - LANG=zh_CN.UTF-8
    volumes:
      - /Users/ever/dev/data/var/mysql/:/var/lib/mysql
      - /Users/ever/dev/data/var/mysql-conf/my.cnf:/etc/mysql/my.cnf
    ports:
        - "3306:3306"

